name: scipy18jlab
channels:
  - conda-forge
  - defaults
dependencies:
  - arrow
  - bqplot
  - cookiecutter
  - dask-core
  - dask
  - decorator
  - entrypoints
  - future
  - ipydatawidgets
  - ipykernel
  - ipyscales
  - ipython
  - ipython_genutils
  - ipyvolume
  - ipywebrtc
  - ipywidgets
  - jedi
  - jinja2
  - jinja2-time
  - jpeg
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyterlab
  - jupyterlab_launcher
  - libpng
  - llvm-meta
  - llvmdev
  - matplotlib
  - nbformat
  - networkx
  - nodejs
  - notebook
  - pandas
  - pexpect
  - pickleshare
  - pillow
  - poyo
  - prompt_toolkit
  - pygments
  - python=3.6.5
  - python-dateutil
  - pythreejs
  - pytz
  - pywavelets
  - pyzmq
  - requests
  - scikit-image
  - setuptools
  - terminado
  - testpath
  - toolz
  - tornado
  - traitlets
  - traittypes
  - urllib3
  - wheel
  - whichcraft
  - widgetsnbextension
  - xz
  - pip
  - scipy
  - pip:
    - dask==0.18.1
